CREATE TABLE "SEATA_ORDER"."T_ORDER"
(
    "ID"         VARCHAR(32) NOT NULL,
    "USER_ID"    VARCHAR(32),
    "PRODUCT_ID" VARCHAR(32),
    "COUNT"      INTEGER,
    "MONEY"      DECIMAL(22, 6),
    "STATUS"     INT DEFAULT 0,
    NOT          CLUSTER PRIMARY KEY("ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT
ON COLUMN "SEATA_ORDER"."T_ORDER"."STATUS" IS '状态';
COMMENT
ON COLUMN "SEATA_ORDER"."T_ORDER"."ID" IS '主键';
COMMENT
ON COLUMN "SEATA_ORDER"."T_ORDER"."USER_ID" IS '用户ID';
COMMENT
ON COLUMN "SEATA_ORDER"."T_ORDER"."PRODUCT_ID" IS '商品ID';
COMMENT
ON COLUMN "SEATA_ORDER"."T_ORDER"."COUNT" IS '数量';
COMMENT
ON COLUMN "SEATA_ORDER"."T_ORDER"."MONEY" IS '金额';


CREATE TABLE "SEATA_ORDER"."UNDO_LOG"
(
    "ID"            BIGINT IDENTITY(1, 1) NOT NULL,
    "BRANCH_ID"     BIGINT       NOT NULL,
    "XID"           VARCHAR(100) NOT NULL,
    "CONTEXT"       VARCHAR(128) NOT NULL,
    "ROLLBACK_INFO" BLOB         NOT NULL,
    "LOG_STATUS"    INT          NOT NULL,
    "LOG_CREATED"   TIMESTAMP(0) NOT NULL,
    "LOG_MODIFIED"  TIMESTAMP(0) NOT NULL,
    "EXT"           VARCHAR(100),
    NOT             CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "UX_UNDO_LOG" UNIQUE ("XID", "BRANCH_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

CREATE UNIQUE INDEX "PRIMARY" ON "SEATA_ORDER"."UNDO_LOG" ("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR);

