CREATE TABLE "SEATA_STORAGE"."STORAGE"
(
    "ID"         VARCHAR(32) NOT NULL,
    "PRODUCT_ID" VARCHAR(32),
    "TOTAL"      INT,
    "USED"       INT,
    "RESIDUE"    INT,
    NOT          CLUSTER PRIMARY KEY("ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT
ON COLUMN "SEATA_STORAGE"."STORAGE"."ID" IS '主键';
COMMENT
ON COLUMN "SEATA_STORAGE"."STORAGE"."PRODUCT_ID" IS '商品ID';
COMMENT
ON COLUMN "SEATA_STORAGE"."STORAGE"."TOTAL" IS '总数';
COMMENT
ON COLUMN "SEATA_STORAGE"."STORAGE"."USED" IS '已使用';
COMMENT
ON COLUMN "SEATA_STORAGE"."STORAGE"."RESIDUE" IS '剩余';


CREATE TABLE "SEATA_STORAGE"."UNDO_LOG"
(
    "ID"            BIGINT IDENTITY(1, 1) NOT NULL,
    "BRANCH_ID"     BIGINT       NOT NULL,
    "XID"           VARCHAR(100) NOT NULL,
    "CONTEXT"       VARCHAR(128) NOT NULL,
    "ROLLBACK_INFO" BLOB         NOT NULL,
    "LOG_STATUS"    INT          NOT NULL,
    "LOG_CREATED"   TIMESTAMP(0) NOT NULL,
    "LOG_MODIFIED"  TIMESTAMP(0) NOT NULL,
    "EXT"           VARCHAR(100),
    NOT             CLUSTER PRIMARY KEY("ID"),
    CONSTRAINT "UX_UNDO_LOG" UNIQUE ("XID", "BRANCH_ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

CREATE UNIQUE INDEX "PRIMARY" ON "SEATA_STORAGE"."UNDO_LOG" ("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR);

